//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 6/30/14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawMagnifyWithWidth: (CGFloat)width;
+ (void)drawRoundRectViewWithShadowWithFrame: (CGRect)frame;

@end
